@host = http://localhost:5240

POST {{host}}/api/customers
Content-Type: application/json

{
  "name": "Jeffry Hermanto",
  "email": "jeffry@somewhere.com",
  "phone": "+62 821 7777 1078"
}

###